# Generated by Django 4.2.19 on 2025-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transmission', models.CharField(max_length=20)),
                ('phoneNumber', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
            ],
        ),
    ]
